name: EDS Logger

on:
  schedule: 
  # 使用的UTC时间
  # 北京时间=UTC + 8 => UTC = 北京时间 - 8
  # 每周一10:15（北京时间）执行一次
  - cron: '15 2 * * 1'

# jobs 是总的，可以包含多个工作流
jobs:

  # 工作流
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
