name: EDS Logger

on:
  push:
  schedule: 
  # 使用的UTC时间
  # 北京时间=UTC + 8 => UTC = 北京时间 - 8
  # 每周一10:15（北京时间）执行一次
  - cron: '15 2 * * 1'

# jobs 是总的，可以包含多个工作流
jobs:

  # 工作流
  do-log:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    # uses 和 run 不能在一个步骤里

    - name: Run
      env:
        GOPATH: $GITHUB_WORKSPACE
        id: ${{ secrets.EDS_LOGIN_ID }}
        pwd: ${{ secrets.EDS_LOGIN_PWD }}
        cookie: ${{ secrets.EDS_LOGIN_COOKIE }}
        # 时区设置为上海
        TZ: Asia/Shanghai
      run: |
        cd widget/edslogger/src/main 
        go run main_action.go -i $id -p $pwd -c $cookie
